name: ESPHome Builder
description: Builds ESPHome binaries

inputs:
  yaml_file:
    description: YAML file to use
    required: true
  version:
    description: Version of ESPHome to build
    required: false
    default: latest
  platform:
    description: Platform (OS/Arch) to use
    required: false
    default: linux/amd64
  cache:
    description: Cache build directory
    required: false
    default: false

outputs:
  name:
    description: Name of device extracted from configuration
    value: ${{ steps.build-step.outputs.name }}
  version:
    description: ESPHome version
    value: ${{ steps.build-step.outputs.esphome-version }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
      with:
        platforms: ${{ inputs.platform }}
    - name: Build ESPHome image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ${{ github.action_path }}
        load: true
        tags: esphome:${{ inputs.version }}
        build-args: VERSION=${{ inputs.version }}
        platforms: ${{ inputs.platform }}
    - if: ${{ inputs.cache == 'true' }}
      id: data-dir
      shell: bash
      run: |
        data_dir=$(dirname ${{ inputs.yaml_file }})/.esphome
        echo "data_dir=$data_dir" >> $GITHUB_OUTPUT
    - if: ${{ inputs.cache == 'true' }}
      name: Cache platformio directory
      uses: actions/cache@v4.0.0
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-esphome-${{ inputs.yaml_file }}-${{ inputs.version }}-platformio
    - if: ${{ inputs.cache == 'true' }}
      name: Cache build directory
      uses: actions/cache@v4.0.0
      with:
        path: ${{ steps.data-dir.outputs.data_dir }}/build
        key: ${{ runner.os }}-esphome-${{ inputs.yaml_file }}-${{ inputs.version }}-build
        save-always: true
    - if: ${{ inputs.cache == 'true' }}
      name: Cache storage directory
      uses: actions/cache@v4.0.0
      with:
        path: ${{ steps.data-dir.outputs.data_dir }}/storage
        key: ${{ runner.os }}-esphome-${{ inputs.yaml_file }}-${{ inputs.version }}-storage
        save-always: true
    - name: Run container
      shell: bash
      id: build-step
      run: |-
        docker run --rm \
        --platform ${{ inputs.platform }} \
        --workdir /github/workspace \
        -v "$(pwd)":"/github/workspace" -v "$HOME:$HOME" \
        --user $(id -u):$(id -g) \
        -e INPUT_YAML_FILE -e HOME \
        -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY \
        -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER \
        -e GITHUB_ACTOR -e GITHUB_OUTPUT \
        -e GITHUB_ACTIONS=true -e CI=true \
        esphome:${{ inputs.version }} \
        ${{ inputs.yaml_file }}

branding:
  icon: "archive"
  color: "white"
